FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /root
COPY requirements.txt requirements.test.txt pyproject.toml pytest.ini ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements.test.txt

WORKDIR /app
